services:

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306

  app:
    build: .
    container_name: app
    image: app
    environment:
      MYSQL_URL: 'root:password@tcp(mysql:3306)/db'
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  my-db:
